# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a527d99b0ceee5e9b72e369f2c385b226fb835f3d204157ee9177451bb09288187342971d577d20356722acc8b9dfede1b591f41daff9f6cde0e41e3a5d4caa

test:
  secret_key_base: 714cc46491eaeec75541df52855129fa0386dd3b9277d398b587db5b1d28aabaea835b641459810b9675d6c84ffa1df5d928756619df5b7128e804fb8ab993f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
